### ISSUE TITLE
Provide an additional identifier associated with pwSafe for data copied to the clipboard

### ISSUE THREAD

**Issue by uup4** [jpvasquez/pwSafe_issues#118]
1Password currently identifies data it puts on the clipboard as data copied from 1Password, which allows the popular clipboard manager app Copied to see that and ignore storing or viewing sensitive data such as passwords.

PwSafe should also do this in the next release. The Copied developer will then provide the same feature to ignore sensitive data from pwSafe.

**Comment by jpvasquez** [comment]
Coming in 8.9
