### ISSUE TITLE
Make truncation in viewing large notes correspond to PC PasswordSafe

### ISSUE THREAD

**Issue by uup4** [jpvasquez/pwSafe_issues#14]
i.e. 30,000 characters is what I believe PC PasswordSafe uses for where large Notes being viewed are truncated.

**Comment by jpvasquez** [comment]
The current solution seems to be fine. You ca still copy the whole notes and paste it in a proper long text editor.

**Comment by uup4** [comment]
True, but it would be much better to maintain a uniform user experience across iOS and PC app. If one shows less text than the other for the same Entry, the user may instead think something went wrong somewhere.

What is the truncation size for viewing that pwSafe uses? Can't iOS easily handle 30,000 characters like the PC PasswordSafe? Isn't this also an easy fix?
