### ISSUE TITLE
Cursor does not appear where tapped as it should while editing the Notes of an Entry

### ISSUE THREAD

**Issue by uup4** [jpvasquez/pwSafe_issues#18]
This issue is not apparent on first creation of the Entry, but occurs after it has been created and is being edited.

**Comment by uup4** [comment]
This is an high severity bug in my view.

**Comment by jpvasquez** [comment]
Actually, the issue is not apparent for new text, just for existing text. New entries have no text. 

Also, this is an iOS bug. I'll try to work around it.

**Comment by uup4** [comment]
Okay. 

I don't see this issue in other apps, so I'm not so sure that it's an iOS issue.

**Comment by jpvasquez** [comment]
I fixed it!

**Comment by uup4** [comment]
Awesome!!!

Thank you.
