### ISSUE TITLE
Create crash feedback system

### ISSUE THREAD

**Issue by jpvasquez** [jpvasquez/pwSafe_issues#25]
1. Create a new device id, store it, and set it as the crashlytics user identifier
1. Send this device id to a new backendMessage call
1. Modify backendMessage handler on the server to use this ID when present

This will allow me to contact affected users of a specific crash without violating their privacy,

**Comment by uup4** [comment]
Will user be able to opt in/out of crash reporting?

**Comment by jpvasquez** [comment]
He already is. See pwSafe's options on the settings app.

**Comment by uup4** [comment]
Okay. Good to know.
