### ISSUE TITLE
Safe backups are not being created

### ISSUE THREAD

**Issue by uup4** [jpvasquez/pwSafe_issues#32]
Safe bakups are not being created for either Unsynced safes or iCloud Drive safes. So when a Restore from backup is attempted, there is no backup to chose.

**Comment by jpvasquez** [comment]
If you create a safe and do nothing to it, thereby leaving it empty, no backup will be created, because there's no useful information to be backed up other than the safe's name.

Otherwise, backups are being created normally.

**Comment by uup4** [comment]
That's not what I'm seeing. I haven't seen a backup since around September 12th. Maybe the backups are there, but I have too many in my list when I do Restore backups and the app doesn't show the most recent ones?

**Comment by jpvasquez** [comment]
I'll do some further investigation then.
