### ISSUE TITLE
Enable safe wide password history by default for new safes 

### ISSUE THREAD

**Issue by uup4** [jpvasquez/pwSafe_issues#33]
Currently creating a new safe does not enable saving of password history by default. The user must do this per entry. 

I would recommend pwSafe behavior be to enable saving of password history on new safe creation by default. Or alternatively, provide the option in the settings page for the user to enable password history and the number of passwords to save (i.e. implement this feature that is already part of PC PasswordSafe)

One reason is that in a touch screen device like an iPhone it is very easy to register accidental touches. For example, if the user unintentionally tap the 'New' button next the Password field while attempting to edit an entry Notes field, they might lose the entry password if password history is not being kept on that entry. So, making saving of password history a default behavior is, I think, a good choice for pwSafe users.

**Comment by jpvasquez** [comment]
I prefer to stick with Password Safe's default for consistency. You can always enable the history for all entries on a safe (including future ones) using the settings menu on the groups screen.

**Comment by uup4** [comment]
You're right. I forgot that it was already possible to set password history for all entries and future ones. But enabling it by default is something I think even PC password safe should be doing. I bet if you did a poll, you'd find most PC password safe users turn on password history.
