### ISSUE TITLE
Delete Unsynched safe backup feature needed

### ISSUE THREAD

**Issue by uup4** [jpvasquez/pwSafe_issues#35]
A settings page option is needed for user to delete Unsynced safes backups if so desired. Currently I do not see a way to remove an Unsynced safe backup from the device. 

I envision this would work like the Restore backups feature, except the action is to delete the backups the user selected if the main safe has already been deleted.

**Comment by jpvasquez** [comment]
It's awkward, and suboptimal, but you can do that by uninstalling the app. I will only implement this if there's enough demand for it on UserVoice.

**Comment by uup4** [comment]
Okay, but I don't really follow why this feature would be awkward and suboptimal. 

I think having to uninstall the app and reinstall is more awkward because you lose everything.

**Comment by jpvasquez** [comment]
Awkward and suboptimal is how I see the current "solution" of uninstalling the app.
