### ISSUE TITLE
Backups not being created for Unsynced safes continued 

### ISSUE THREAD

**Issue by uup4** [jpvasquez/pwSafe_issues#40]
I am certain that in my TestFlight v8.1.3 the settings page Restored backups screen is not showing any backups for non-empty Unsynced safes I've created and deleted. 

Below are some steps I took to verify this. 

I managed to delete all old safe backups from before v8.1.3 that were being shown by restoring them then deleting the restored safes. Once I did that my Restored backup screen for Unsynced safes became empty. Then I created a new non-empty Unsynced safe, closed the safe, quit pwSafe, reopened pwSafe, and finally deleted the new safe. Then I checked the Restored backups screen in settings and it was still empty.

**Comment by uup4** [comment]
Btw, 

The Restored backups screen is empty for both the Unsynced safe and iCloud section even though I have current safes in both device and iCloud.

**Comment by uup4** [comment]
This issue is still there for me in v8.1.4.

Could it be due to an iOS setting?

**Comment by jpvasquez** [comment]
No. Can you please:

- Open pwSafe
- Change your safe in any way
- Go back to the home screen
- Send me a support request

This will include logs I can inspect to find out what went wrong with the backups.

Before doing that, please open pwSafe Cloud settings and double-check that Cloud Backups is enabled.

Thanks!

**Comment by uup4** [comment]
I'm not subscribed to the Cloud Backups service.

**Comment by jpvasquez** [comment]
I somehow misunderstood this to be related to Cloud Backups, not the restore backups system. Sorry, I'll look to the right direction now.

**Comment by uup4** [comment]
Okay. No problemo!
