### ISSUE TITLE
The truncate limit for viewing large notes is too small.

### ISSUE THREAD

**Issue by uup4** [jpvasquez/pwSafe_issues#41]
I tested it. Seems like it's about 5400 characters. That's too small. 

It should at least match the 32K character limit PC PasswordSafe uses for truncating display of large notes.

**Comment by jpvasquez** [comment]
The limit on iOS is not about character count, but about maximum height, which is what makes the notes field not to be displayed.

**Comment by uup4** [comment]
Even still, I'm guessing that 32k characters should not be a problem. 

The test case that caused me to first report this issue was 10 times larger, which I agree is unreasonably large.
