### ISSUE TITLE
Typing a space does not immediately echo in the Default Username

### ISSUE THREAD

**Issue by uup4** [jpvasquez/pwSafe_issues#62]
On the new safe settings page, when a space character is typed in the Default Username, it does not immediately echo. It's only after the next non-space character is typed that you see the spaces that were typed.

**Comment by uup4** [comment]
I don't see any gear icon to assign a label. Maybe I'm not authorized for the capability to assign labels?

**Comment by jpvasquez** [comment]
The space thing is an iOS bug / feature. In any case, I'll trim spaces from both sides of the username before saving.
