### ISSUE TITLE
Password history changes on the safe settings page not immediately updating entries

### ISSUE THREAD

**Issue by uup4** [jpvasquez/pwSafe_issues#69]
'Update all entries' password history on the safe settings page is not updating the entries password history right away. The updates happens only after exiting the safe (i.e. Go all the way back to the list of safes screen but not closing the safe) then after opening or reentering the safe the updates are reflected in the entries.

**Comment by jpvasquez** [comment]
Fixed by jpvasquez/pwSafe@5b1a5099455bd6e23d8f577a650975bf7d111da5
