### ISSUE TITLE
Text box for typing password when deleting a safe cuts off letters like 'q', 'g' and 'j'

### ISSUE THREAD

**Issue by uup4** [jpvasquez/pwSafe_issues#70]
This was fixed in v8.1.6 for the master password text box.

On the safes screen, if you delete a safe or unlink a safe from Dropbox that is locked and have to type the safe password, the safe password text box that pops up cuts off the bottom of letters like 'g', 'q', 'j' by about a pixel.

**Comment by jpvasquez** [comment]
That's an iOS bug.
