### ISSUE TITLE
'How can we help you' text area starts with a blank line. 

### ISSUE THREAD

**Issue by uup4** [jpvasquez/pwSafe_issues#72]
Using the keyboard 'Next' button to go from 'Email Address' to 'How can we help you' text area results in the cursor starting on the second line (i.e. The first line will be blank if user starts typing from where the cursor starts).

There is no first blank line if the user simply taps in the empty 'How can we help you' text area before starting to type.

**Comment by jpvasquez** [comment]
Fixed by jpvasquez/pwSafe@9b494a25fd1c75e62e21db5d6c1086696efeaaf8
