### ISSUE TITLE
Center keyboard type icon on safe settings password keyboard

### ISSUE THREAD

**Issue by uup4** [jpvasquez/pwSafe_issues#74]
There is a little room there to center the keyboard type icon on the safe settings screen keyboard when changing safe password. Right now it's positioned closer to the 'Done' button on the right.

**Comment by jpvasquez** [comment]
I prefer it like this, so that it doesn't mix up with the navigation arrows.

**Comment by uup4** [comment]
I don't think it would be confused.

It's not a big deal though.
