### ISSUE TITLE
The Safe Settings Password History screen needs a 'Done' button

### ISSUE THREAD

**Issue by uup4** [jpvasquez/pwSafe_issues#80]
The Safe Settings Password History screen has only a back button which also applies any changes made in that screen. This is not intuitive and consistent with how other configuration screws work. 

I think it should have a 'Done' button in the top right corner that applies the changes and the back button would serve as an exit without applying any changes made if 'Done' was never tapped.

**Comment by jpvasquez** [comment]
Changes are only committed when you tap Done on the settings screen.

**Comment by uup4** [comment]
Okay, you're right. That's good. 

For whatever reason I thought the changes were being committed before that.
