### ISSUE TITLE
Master Password is bypassed by Safari extension

### ISSUE THREAD

**Issue by uup4** [jpvasquez/pwSafe_issues#83]
Not sure if this is by design or not, but if Master Password is enabled and even set to Ask always, the Safari Extension will work and Master Password is completely bypassed.

**Comment by jpvasquez** [comment]
It's by design. The last thing I want is to add a new roadblock when using the extension.

**Comment by uup4** [comment]
Not sure I agree. I would think that people using master password would expect that it can't be bypassed and probably would accept the fact that they need to enter their master password before the extension runs.
