### ISSUE TITLE
Setting safe settings indexing to 'Everything' and iOS search does not find search term in Notes

### ISSUE THREAD

**Issue by uup4** [jpvasquez/pwSafe_issues#86]
Not sure what the 'Everything' setting implies, but one test I did with a special term in the Notes and then an iOS search did not find it.

**Comment by jpvasquez** [comment]
Everything but notes and password. I don't know how to convey that in a short text.

**Comment by uup4** [comment]
Or instead, why not just add a descriptive  label on this screen to state exactly what fields 'Everthing' indexes. 

And I wouldn't state it as 'Everything but notes and passwords' since you'll get a question of does it include this or that. Just make the description explicit.
